name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            libgrpc++-dev \
            libgtest-dev \
            libprotobuf-dev \
            ninja-build \
            protobuf-compiler \
            protobuf-compiler-grpc

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
